### PR TITLE
Redesigning the menus

### PR DESCRIPTION
**Pull request by idoash4**
http://imgur.com/a/jOOGl

It is a bit better now. I am open for more suggestions.

### CODE REVIEW

**Comment by ghost** [comment]
Damn that's nice.

Don't know how useful that Namelayer help menu is. I can never remember
what the commands stand for. Maybe show the regular versions instead of the
aliases.

**Comment by rourke750** [comment]
It gives help when hovering over. When I get the chance I'll look it over.

**Comment by idoash4** [comment]
As rourke said hovering over a command will explain what it does and how to use it. http://imgur.com/BXkiRU0

**Comment by ttk2** [comment]
so will the automatic advice text things be handled similarly?

**Comment by idoash4** [comment]
The automatic advices are not coded yet. They require changes in the code of most of our plugins. The changes here only require minor changes in the yml files of some of our plugins.

**Comment by ttk2** [comment]
how is a player supposed to know hovering does anything?

**Comment by rourke750** [comment]
@BlackXnt Is this tested?

**Comment by idoash4** [comment]
@rourke750 yes

@ttk2 I think it is pretty obvious. The commands in the menus look like buttons.

**Comment by rourke750** [comment]
Anyways I think these are really nice changes.  Anything you want to add or good for merge?

**Comment by idoash4** [comment]
good for merge

**Comment by idoash4** [comment]
Please merge all the other pulls I made and put them on civtest.

**Comment by ttk2** [comment]
that's going to be a pain. is thee just one for everything? I didn't keep track.

**Pull request merged**
