### PR TITLE
Fixing teleporting after respawning

### PR DESCRIPTION
**Pull request by Maxopoly**
Fixing: https://github.com/Civcraft/CivMenu/issues/6

@BlackXnt

### CODE REVIEW

**Comment by idoash4** [comment]
This is good thanks!

**Comment by ttk2** [comment]
so just merge?

**Comment by idoash4** [comment]
@Maxopoly Did you test this?

**Comment by suirad** [comment]
Please see #9

**Comment by Maxopoly** [comment]
Replaced by https://github.com/Civcraft/CivMenu/pull/9

**Pull request closed without merging**
